name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install submodule
      run: git submodule update --init --recursive
    - name: Install dependencies
      run: poetry install --no-root
    - name: Build figures
      run: make all -j 3
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: output/*.svg
